
name: aiopyo365-release
on:
  push:
    tags:
      - v.**
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.1'
      - name: Build Project with poetry
        run: poetry build
